version: '3'

services: 
  postgres_1:
    build: 
      context: .
      dockerfile: postgres.dockerfile
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi
  api:
    build: 
      context: .
      dockerfile: backend.dockerfile
    depends_on: 
      - postgres_1
    environment: 
      - PYTHONPATH=/backend_fastapi/app
    working_dir: /backend_fastapi
    volumes: 
      - ./:/backend_fastapi